---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: data-product-event-listener
spec:
  serviceAccountName: data-product-listener-sa
  triggers:
    - triggerRef: data-product-listener-trigger
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: data-product-listener-trigger
spec:
  bindings:
    - ref: data-product-binding
  template:
    ref: data-product-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: data-product-binding
spec:
  params:
    - name: data-product-name
      value: $(body.data-product-name)
    - name: data-product-domain
      value: $(body.data-product-domain)
    - name: data-product-description
      value: $(body.data-product-description)
    - name: data-product-owner
      value: $(body.data-product-owner)
    - name: data-product-owner-email
      value: $(body.data-product-owner-email)
    - name: data-product-information-sla
      value: $(body.data-product-information-sla)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: data-product-pipeline
spec:
  workspaces:
    - name: data-product-ws
  params:
  - name: data-product-name
    description: The data product name
    default: Data product X
  - name: data-product-domain
    description: The data product domain
    default: Domain X
  - name: data-product-description
    description: The data product description
    default: This data product...
  - name: data-product-owner
    description: The data product owner
    default: Owner
  - name: data-product-owner-email
    description: The data product owner email
    default: owner@airbus.com
  - name: data-product-information-sla
    description: SLA for receiving the data product information
    default: 24 hours
  tasks:
    - name: clone-template-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/ardlema/data-product-template.git
      workspaces:
        - name: output
          workspace: data-product-ws
    - name: create-repo
      taskRef:
        name: create-repo
      runAfter:
        - clone-template-repo
      params:
        - name: data-product-name
          value: "$(params.data-product-name)"
    - name: replace-template-placeholders
      taskRef:
        name: modify-template
      runAfter:
        - create-repo
      params:
        - name: data-product-name
          value: "$(params.data-product-name)"
        - name: data-product-domain
          value: $(params.data-product-domain)
        - name: data-product-description
          value: $(params.data-product-description)
        - name: data-product-owner
          value: $(params.data-product-owner)
        - name: data-product-owner-email
          value: $(params.data-product-owner-email)
        - name: data-product-information-sla
          value: $(params.data-product-information-sla)
        - name: data-product-github-url
          value: $(tasks.create-repo.results.repourl)
      workspaces:
        - name: data-product-ws
          workspace: data-product-ws
    - name: push-repo
      taskRef:
        name: git-push
      runAfter:
        - replace-template-placeholders
      params:
        - name: repourl
          value: "$(tasks.create-repo.results.repourl)"
      workspaces:
        - name: data-product-ws
          workspace: data-product-ws
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: data-product-template
spec:
  params:
  - name: data-product-name
    description: The data product name
    default: Data product X
  - name: data-product-domain
    description: The data product domain
    default: Domain X
  - name: data-product-description
    description: The data product description
    default: This data product...
  - name: data-product-owner
    description: The data product owner
    default: Owner
  - name: data-product-owner-email
    description: The data product owner email
    default: owner@airbus.com
  - name: data-product-information-sla
    description: SLA for receiving the data product information
    default: 24 hours
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: data-product-pipeline-run-
      spec:
        serviceAccountName: data-product-listener-sa
        pipelineRef:
          name: data-product-pipeline
        params:
          - name: data-product-name
            value: $(tt.params.data-product-name)
          - name: data-product-domain
            value: $(tt.params.data-product-domain)
          - name: data-product-description
            value: $(tt.params.data-product-description)
          - name: data-product-owner
            value: $(tt.params.data-product-owner)
          - name: data-product-owner-email
            value: $(tt.params.data-product-owner-email)
          - name: data-product-information-sla
            value: $(tt.params.data-product-information-sla)
        workspaces:
          - name: data-product-ws # this workspace name must be declared in the Pipeline
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
                resources:
                  requests:
                    storage: 1Gi