---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: data-product-event-listener
spec:
  serviceAccountName: data-product-listener-sa
  triggers:
    - triggerRef: data-product-listener-trigger
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: data-product-listener-trigger
spec:
  bindings:
    - ref: data-product-binding
  template:
    ref: data-product-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: data-product-binding
spec:
  params:
    - name: greeting
      value: $(body.greeting)
    - name: data-product-name
      value: $(body.data-product-name)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: data-product-pipeline
spec:
  workspaces:
    - name: data-product-ws
  params:
  - name: greeting
    description: A dummy parameter
    default: Data product X
  - name: data-product-name
    description: The data product name
    default: Data product X
  tasks:
    - name: clone-template-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/ardlema/data-product-template.git
      workspaces:
        - name: output
          workspace: data-product-ws
    - name: replace-template-placeholders
      taskRef:
        name: modify-template
      runAfter:
        - clone-template-repo
      params:
        - name: greeting
          value: "$(params.greeting)"
      workspaces:
        - name: data-product-ws
          workspace: data-product-ws
    - name: create-repo
      taskRef:
        name: create-repo
      runAfter:
        - replace-template-placeholders
      params:
        - name: data-product-name
          value: "$(params.data-product-name)"
    - name: git-push
      taskRef:
        name: git-push
      runAfter:
        - create-repo
      params:
        - name: repourl
          value: "$(tasks.create-repo.results.repourl)"
      workspaces:
        - name: data-product-ws
          workspace: data-product-ws
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: data-product-template
spec:
  params:
  - name: greeting
    description: The data product
    default: Data product X
  - name: data-product-name
    description: The data product name
    default: Data product X
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: data-product-pipeline-run-
      spec:
        serviceAccountName: data-product-listener-sa
        pipelineRef:
          name: data-product-pipeline
        params:
          - name: greeting
            value: $(tt.params.greeting)
          - name: data-product-name
            value: $(tt.params.data-product-name)
        workspaces:
          - name: data-product-ws # this workspace name must be declared in the Pipeline
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
                resources:
                  requests:
                    storage: 1Gi